---
- name: Ensure required MySQL Python module is installed and query all users in MySQL
  hosts: fileserver
  collections:
    - community.mysql
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_hostname: 10.2.77.103
    mysql_port: 3306
    mysql_root_user: discover_node
    mysql_root_password: discover@123
    mysql_db_name: hmdb_test
    mysql_table_name: discover_node
    employee_data:
      orion_node_ip_address: "{{ orion_node_ip_address }}"
      orion_node_caption_name: "{{ orion_node_caption_name }}" 
      orion_node_polling_method: "{{ orion_node_polling_method }}"
      orion_node_sys_name: "{{ orion_node_sys_name }}"
      orion_node_machine_name: "{{ orion_node_machine_name }}"
      orion_node_vendor_name: "{{ orion_node_vendor_name }}"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Query all users in MySQL
      mysql_query:
        login_host: "{{ mysql_hostname }}"
        login_port: "{{ mysql_port }}"
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
        login_db: "{{ mysql_db_name }}"
        query: "INSERT INTO {{ mysql_table_name }} (orion_node_ip_address, orion_node_caption_name, orion_node_polling_method, orion_node_sys_name, orion_node_machine_name, orion_node_vendor_name)
          VALUES ('{{ employee_data.orion_node_ip_address }}', '{{ employee_data.orion_node_caption_name }}', '{{ employee_data.orion_node_polling_method }}', '{{ employee_data.orion_node_sys_name }}', '{{ employee_data.orion_node_machine_name }}', '{{ employee_data.orion_node_vendor_name }}')"
      register: query_result

    - name: Output query results
      debug:
        var: query_result.results
